collate_fn: nn.dataset.collate_fn.default_collate_inference
data_arg:
  batch_size: 1
  dataset: nn.dataset.subseq_feeder.SubseqFeeder
  drop_last: false
  num_workers: 1
  shuffle: false
  test_dataset_arg:
    binary: false
    data_path: ./resources/data/fit/inference/rnnv3_nolabel/data.pkl
    label_path: ./resources/data/fit/inference/rnnv3_nolabel/label.pkl
    random_seed: 404
    subseq_len: 384
    use_random_iter: true
    inference: true
model_arg:
  model_type: nn.net.cganv4.Generator
  compressed_channels: 16
  in_channels: 514
  noise_in_channels: 3
  num_classes: 3
  output_len: 384
num_classes: 3
output_arg:
  log_dir: ./resources/result/cganv4/0.1/%d
  model_save_dir: ./resources/result/cganv4/0.1/%d
  model_save_step: 16
output_device: 0
pred_arg:
  pred_type: nn.pred.multi_pred.MultiPred
train_type: gan
noise_size:
  - 1
  - 384
  - 3
weights_path: ./resources/result/cganv4/0.1/1/model_0_epoch_63.pt
model_eval_mode: false
random_seed: 101
