collate_fn: dataset.collate_fn.data_array_to_tensor_inference
output_collate_fn: dataset.collate_fn.output_collate_fn
data_arg:
  batch_size: 1
  dataset: dataset.mel_db_dataset.MelDBDataset
  drop_last: false
  num_workers: 1
  shuffle: false
  test_dataset_arg:
    audio_dir: ./resources/data/inference_mel
    db_path: ./resources/data/osu_inference_mel.db
    inference: true
    pad_beats: 4
    sample_beats: 16
    snap_mel: 4
    snap_offset: 0
    snap_divisor: 8
    table_name: INFERENCE
model_arg:
  extract_hidden_layer_num: 2
  model_type: net.mel_mlp.MelMLP
  n_mel: 128
  num_classes: 2
  pad_beats: 4
  sample_beats: 16
  snap_divisor: 8
  snap_mel: 4
output_device: 0
pred_arg:
  pred_type: pred.multi_pred.MultiPred
weights_path: './resources/result/mel_mlp_bi_lr0.1/0.1/1/model_epoch9.pt'
