cal_acc_func: nn.metrics.multi_pred_metrics.multi_pred_cal_acc_func
cal_cm_func: nn.metrics.multi_pred_metrics.multi_pred_cal_cm_func
collate_fn: nn.dataset.collate_fn.default_collate_inference
data_arg:
  batch_size: 6
  dataset: nn.dataset.subseq_feeder.SubseqFeeder
  drop_last: false
  num_workers: 1
  shuffle: false
  test_dataset_arg:
    binary: false
    data_path: ./resources/data/fit/inference/rnnv3_nolabel/data.pkl
    label_path: ./resources/data/fit/inference/rnnv3_nolabel/label.pkl
    random_seed: 404
    subseq_len: 384
    use_random_iter: false
    inference: true
model_arg:
  model_type: nn.net.seqganv1.Generator
  cond_data_feature_dim: 514
  embedding_dim: 256
  hidden_dim: 512
  vocab_size: 3
num_classes: 3
output_arg:
  log_dir: ./resources/result/seqganv1/0.1/%d
  model_save_dir: ./resources/result/seqganv1/0.1/%d
  model_save_step: 8
output_device: 0
pred_arg:
  pred_type: nn.pred.multi_pred.MultiPred
random_seed: 404
weights_path: ./resources/result/seqganv1/0.01/1/model_0_epoch_-1.pt
