cal_acc_func: nn.metrics.multi_pred_metrics.multi_pred_cal_acc_func
cal_cm_func: nn.metrics.multi_pred_metrics.multi_pred_cal_cm_func
collate_fn: nn.dataset.collate_fn.default_collate_inference
data_arg:
  batch_size: 1
  dataset: nn.dataset.subseq_density_feeder.SubseqFeeder
  drop_last: false
  num_workers: 1
  shuffle: false
  test_dataset_arg:
    binary: false
    data_path: ./resources/data/fit/inference/label_pos/data.pkl
    ho_pos: true
    label_path: ./resources/data/fit/inference/label_pos/label.pkl
    random_seed: 404
    subseq_len: 384
    inference: true
    use_random_iter: false
model_arg:
  cond_data_feature_dim: 514
  dec_layers: 2
  enc_layers: 2
  hidden_dim: 512
  in_channels: 4
  model_type: nn.net.vaev4.VAE
  pos_emb_channels: 8
  pos_emb_period: 48
  step_snaps: 8
num_classes: 3
output_arg:
  log_dir: ./resources/result/vaev3/0.001/%d
  model_save_dir: ./resources/result/vaev3/0.001/%d
  model_save_step: 8
output_device: 0
pred_arg:
  pred_type: nn.pred.multi_pred.MultiPred
random_seed: 404
train_type: vae
weights_path: ./resources/result/vaev4/0.001/1/model_0_epoch_63.pt
