cal_acc_func: nn.metrics.multi_pred_metrics.multi_pred_cal_acc_func
cal_cm_func: nn.metrics.multi_pred_metrics.multi_pred_cal_cm_func
collate_fn: nn.dataset.collate_fn.default_collate_inference
data_arg:
  batch_size: 1
  dataset: nn.dataset.subseq_feeder.SubseqFeeder
  drop_last: false
  num_workers: 1
  shuffle: false
  test_dataset_arg:
    binary: false
    data_path: ./resources/data/fit/inference/label_pos/data.pkl
    ho_pos: true
    label_path: ./resources/data/fit/inference/label_pos/label.pkl
    random_seed: 404
    subseq_len: 96
    use_random_iter: false
    inference: true
model_arg:
  cond_data_feature_dim: 514
  hidden_dim: 512
  model_type: nn.net.vaev2.VAE
  num_class: 3
  num_layers: 2
  seq_len: 384
num_classes: 3
output_arg:
  log_dir: ./resources/result/vae/0.001/%d
  model_save_dir: ./resources/result/vae/0.001/%d
  model_save_step: 8
output_device: 0
random_seed: 202
pred_arg:
  pred_type: nn.pred.multi_pred.MultiPred
train_type: vae
weights_path: ./resources/result/vaev2/0.001/1/model_0_epoch_0.pt
