cal_acc_func: metrics.multi_pred_metrics.multi_pred_cal_acc_func
cal_cm_func: metrics.multi_pred_metrics.multi_pred_cal_cm_func
collate_fn: dataset.collate_fn.data_array_to_tensor
data_arg:
  batch_size: 1
  dataset: dataset.mel_db_dataset_c1.MelDBDatasetC1
  drop_last: false
  num_workers: 1
  shuffle: false
  test_dataset_arg:
    audio_dir: ./resources/data/mel
    db_path: ./resources/data/osu_train_mel.db
    density_label: true
    multi_label: true
    pad_beats: 2
    sample_beats: 8
    snap_divisor: 8
    snap_mel: 4
    snap_offset: 0
    table_name: TESTFOLD%d
  train_dataset_arg:
    audio_dir: ./resources/data/mel
    db_path: ./resources/data/osu_train_mel.db
    density_label: true
    multi_label: true
    pad_beats: 2
    sample_beats: 8
    snap_divisor: 8
    snap_mel: 4
    snap_offset: 0
    table_name: TRAINFOLD%d
loss_arg:
  loss_type: loss.multi_reg_loss.MultiMSELoss
model_arg:
  extract_hidden_layer_num: 1
  model_type: net.mel_mlp_reg_c1.MelMLPRegC1
  n_mel: 128
  pad_beats: 2
  sample_beats: 8
  snap_divisor: 8
  snap_mel: 4
optimizer_arg:
  lr: 0.1
  optimizer_type: SGD
output_arg:
  log_dir: ./resources/result/mel_mlp_density_c1_lr0.1/0.1/%d
  model_save_dir: ./resources/result/mel_mlp_density_c1_lr0.1/0.1/%d
  model_save_step: 4
output_device: 0
pred_arg:
  pred_type: pred.multi_pred.MultiPred
scheduler_arg:
  gamma: 0.1
  scheduler_type: StepLR
  step_size: 2
task_type: regression
train_arg:
  epoch: 16
  eval_step: 1
