cal_acc_func: nn.metrics.multi_pred_metrics.multi_pred_cal_acc_func
cal_cm_func: nn.metrics.multi_pred_metrics.multi_pred_cal_cm_func
collate_fn: nn.dataset.collate_fn.data_array_to_tensor
data_arg:
  batch_size: 1
  dataset: nn.dataset.mel_db_dataset_c1norm.MelDBDatasetC1Norm
  drop_last: false
  num_workers: 1
  shuffle: false
  test_dataset_arg:
    audio_dir: ./resources/data/mel
    db_path: ./resources/data/osu_train_mel.db
    multi_label: true
    pad_beats: 4
    sample_beats: 16
    snap_divisor: 8
    snap_mel: 4
    snap_offset: 0
    switch_label: true
    table_name: TESTFOLD%d
  train_dataset_arg:
    audio_dir: ./resources/data/mel
    db_path: ./resources/data/osu_train_mel.db
    multi_label: true
    pad_beats: 4
    sample_beats: 16
    snap_divisor: 8
    snap_mel: 4
    snap_offset: 0
    switch_label: true
    table_name: TRAINFOLD%d
loss_arg:
  loss_type: nn.loss.multi_pred_loss.MultiPredLoss
  weights:
  - 1
  - 10
  - 10
  - 10
model_arg:
  extract_hidden_layer_num: 2
  model_type: nn.net.mel_mlp_c1.MelMLPC1
  n_mel: 128
  num_classes: 4
  pad_beats: 4
  sample_beats: 16
  snap_divisor: 8
  snap_mel: 4
optimizer_arg:
  lr: 0.01
  optimizer_type: SGD
output_arg:
  log_dir: ./resources/result/mel_mlp_c1norm_lr0.01/0.01/%d
  model_save_dir: ./resources/result/mel_mlp_c1norm_lr0.01/0.01/%d
  model_save_step: 1
output_device: 0
pred_arg:
  pred_type: nn.pred.multi_pred.MultiPred
scheduler_arg:
  gamma: 0.1
  scheduler_type: StepLR
  step_size: 1
train_arg:
  epoch: 4
  eval_step: 1
