cal_acc_func: metrics.multi_pred_metrics.multi_pred_cal_acc_func
cal_cm_func: metrics.multi_pred_metrics.multi_pred_cal_cm_func
collate_fn: dataset.collate_fn.data_array_to_tensor
data_arg:
  batch_size: 1
  dataset: dataset.seg_multi_label_db_dataset.SegMultiLabelDBDataset
  drop_last: false
  num_workers: 1
  shuffle: false
  test_dataset_arg:
    audio_dir: ./resources/data/audio
    beat_feature_frames: 16384
    db_path: ./resources/data/osu_train.db
    multi_label: false
    pad_beats: 4
    sample_beats: 16
    table_name: TESTFOLD%d
  train_dataset_arg:
    audio_dir: ./resources/data/audio
    beat_feature_frames: 16384
    db_path: ./resources/data/osu_train.db
    multi_label: false
    pad_beats: 4
    sample_beats: 16
    table_name: TRAINFOLD%d
loss_arg:
  loss_type: loss.multi_pred_loss.MultiPredLoss
model_arg:
  beat_feature_frames: 16384
  extract_hidden_layer_num: 0
  model_type: net.seg_multi_pred_mlp.SegMultiPredMLP
  num_classes: 2
  pad_beats: 4
  sample_beats: 16
optimizer_arg:
  lr: 0.1
  optimizer_type: SGD
output_arg:
  log_dir: ./resources/result/seg_mlp_bi_lr0.1/0.1/%d
  model_save_dir: ./resources/result/seg_mlp_bi_lr0.1/0.1/%d
  model_save_step: 1
output_device: 0
pred_arg:
  pred_type: pred.multi_pred.MultiPred
scheduler_arg:
  gamma: 0.1
  scheduler_type: StepLR
  step_size: 3
train_arg:
  epoch: 24
  eval_step: 1
