cal_acc_func: nn.metrics.valid_itv_metrics.cal_acc_func_valid_itv
cal_cm_func: nn.metrics.valid_itv_metrics.cal_cm_func_valid_itv
collate_fn: nn.dataset.collate_fn.default_collate
data_arg:
  batch_size: 4
  dataset: nn.dataset.subseq_feeder.SubseqFeeder
  drop_last: false
  num_workers: 4
  shuffle: false
  train_dataset_arg:
    binary: false
    data_path: ./resources/data/fit/label_pos/data.pkl
    ho_pos: true
    label_path: ./resources/data/fit/label_pos/label.pkl
    random_seed: 404
    subseq_len: 96
    take_first: 100
    use_random_iter: true
grad_alter_fn: norm
grad_alter_fn_arg:
  max_norm: 10
loss_arg:
  loss_type: nn.loss.valid_itv_loss.ValidIntervalNLLLoss
  weight:
  - 1.0
  - 1.0
  - 1.0
model_arg:
  decoder_args:
    dropout: 0.5
    embed_size: 16
    hidden_size: 256
    n_layers: 1
    output_size: 5
  embed_size: 16
  encoder_args:
    cond_data_feature_dim: 514
    dropout: 0.5
    hidden_size: 256
    n_layers: 2
  model_type: nn.net.seq2seq.Seq2Seq
  num_class: 3
optimizer_arg:
  lr: 0.01
  optimizer_type: Adam
output_arg:
  log_dir: ./resources/result/seq2seq/0.01/%d
  model_save_dir: ./resources/result/seq2seq/0.01/%d
  model_save_step: 1
output_device: 0
pred_arg:
  pred_type: nn.pred.valid_itv_pred.ValidIntervalMultiPred
scheduler_arg:
  gamma: 0.1
  scheduler_type: StepLR
  step_size: 32
test_extra:
  teacher_forcing_ratio: 0
train_arg:
  epoch: 128
  eval_step: 1
train_extra:
  teacher_forcing_ratio: 0.5
train_type: seq2seq
