db_path: ./resources/data/osu_train.db
do_filter: false
do_fold_divide: true
do_preprocess: false
filter_arg:
  filter_arg:
  - filter_type: util.data.filter.HitObjectFilter
  - filter_type: util.data.filter.BeatmapsetSingleAudioFilter
  - filter_type: util.data.filter.SingleBMPFilter
  - filter_type: util.data.filter.SingleUninheritedTimingPointFilter
  filter_type: util.data.filter.OsuTrainDataFilterGroup
fold_divider_arg:
  fold_divider_type: util.data.fold_divider.OsuTrainDBFoldDivider
  folds: 5
  shuffle: false
preprocessor_arg:
  beat_feature_frames: 16384
  preprocessor_type: util.data.preprocessor.ResamplePreprocessor
save_dir: ./resources/data/audio
