do_filter: false
do_fold_divide: true
do_preprocess: false
filter_arg:
  filter_arg:
  - filter_type: preprocess.filter.HitObjectFilter
  - filter_type: preprocess.filter.BeatmapsetSingleAudioFilter
  - filter_type: preprocess.filter.SingleBMPFilter
  - filter_type: preprocess.filter.SingleUninheritedTimingPointFilter
  filter_type: preprocess.filter.OsuTrainDataFilterGroup
fold_divider_arg:
  fold_divider_type: preprocess.fold_divider.OsuTrainDBFoldDivider
  folds: 5
  shuffle: false
preprocessor_arg:
  beat_feature_frames: 16384
  preprocessor_type: preprocess.preprocessor.ResamplePreprocessor
