fit_dataset: true
fit_dataset_arg:
  dataset_type: preprocess.dataset.label_pos_dataset.LabelPosDataset
  save_dir: ./resources/data/fit/inference/label_pos
  audio_mel: 4
  label_num: 3
  snap_divisor: 8
  coeff_speed_stars: 2.5
  coeff_bpm: 120
  switch_label: false
  multibeat_label_fmt: 0
  preprocess_arg:
    beat_feature_frames: 16384
    snap_offset: 0
    n_fft: 1024
    win_length: null
    hop_length: 512
    n_mels: 128
    snap_divisor: 8
    from_resampled: false
inference: true
