db_path: ./resources/data/osu_inference_mel.db
do_filter: false
do_fold_divide: false
do_preprocess: true
preprocessor_arg:
  beat_feature_frames: 16384
  from_resampled: false
  hop_length: 512
  n_fft: 1024
  n_mels: 128
  preprocessor_type: preprocess.preprocessor.MelPreprocessor
  snap_offset: 0
  win_length: null
save_dir: ./resources/data/inference_mel
save_ext: .pkl
inference: true
